import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";


export const metadata: Metadata = {
  title: "SAC-2025",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="font-[Cera-pro] relative">
      <body>
        <div className="absolute inset-0 bg-[url(/backgroundLanding.jpeg)] bg-cover bg-center opacity-25 z-[-1]" />
        <Navbar />
        {children}
      </body>
    </html>
  );

}


